services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432" # used this port cause the default port 5432 is used by local postgres service
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: manabiko-postgres
    environment:
      POSTGRES_USER: manabiko
      POSTGRES_PASSWORD: manabiko
      POSTGRES_DB: manabiko_library
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./api/static:/app/static
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres

volumes:
  pgdata:
