services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: manabiko
      POSTGRES_PASSWORD: manabiko
      POSTGRES_DB: manabiko_library
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./scripts/static:/app/static
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres

volumes:
  pgdata:
